### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by aravol** [PowerOfCode/gwen-dotnet#56]
Would love to see some examples on the wiki in addition to the showcase images

**Comment by TheRealPowerCoder** [comment]
Could you please tell me more of what you had in mind?

Btw there are "examples", just not well documented. You can find them under
[UnitTest](https://github.com/PowerOfCode/gwen-dotnet/tree/master/Gwen.UnitTest)

For the part with "schowcase images": there are some old Screenshots in the [ProjectHome](https://github.com/PowerOfCode/gwen-dotnet/wiki/ProjectHome) of the wiki.

**Comment by benklett** [comment]
As you did not answer PowerCoder's question, I am going to close this issue for now.
